<?php
return [
    "Umberto Eco",
    "Italo Calvino",
    "Virginia Woolf",
    "Clarice Lispector",
    "Marguerite Yourcenar",
    "Simone de Beauvoir",
    "Albert Camus",
    "Jean-Paul Sartre",
    "Charles Baudelaire",
    "Arthur Rimbaud",
    "Fernando Pessoa",
    "José Saramago",
    "Eça de Queirós",
    "Thomas Mann",
    "Hermann Hesse",
    "Stefan Zweig",
    "Günter Grass",
    "Friedrich Nietzsche",
    "Oscar Wilde",
    "James Joyce",
    "Samuel Beckett",
    "William Faulkner",
    "T.S. Eliot",
    "Ezra Pound",
    "Walt Whitman",
    "Emily Dickinson",
    "Edgar Allan Poe",
    "Mark Twain",
    "Henry James",
    "Yukio Mishima",
    "Haruki Murakami",
    "Kenzaburō Ōe",
    "Yasunari Kawabata",
    "Jun'ichirō Tanizaki",
    "José Martí",
    "Rubén Darío",
    "Octavio Paz",
    "Carlos Fuentes",
    "Juan Carlos Onetti",
    "Eduardo Galeano",
    "Roberto Bolaño",
    "Nicanor Parra",
    "Gabriela Mistral",
    "Pablo Neruda",
    "Alejo Carpentier",
    "Lezama Lima",
    "Miguel Ángel Asturias",
    "Augusto Roa Bastos",
    "Horacio Quiroga",
    "Alfonsina Storni"
]
?>