<?php

return[
    "Don Quijote de la Mancha",
    "Cien años de soledad",
    "El señor de los anillos",
    "1984",
    "Un mundo feliz",
    "Fahrenheit 451",
    "Orgullo y prejuicio",
    "Crónica de una muerte anunciada",
    "Rayuela",
    "El amor en los tiempos del cólera",
    "Pedro Páramo",
    "La ciudad y los perros",
    "La tía Julia y el escribidor",
    "La casa de los espíritus",
    "Eva Luna",
    "El túnel",
    "Sobre héroes y tumbas",
    "Abaddón el exterminador",
    "Ficciones",
    "El Aleph",
    "Crimen y castigo",
    "Los hermanos Karamazov",
    "Guerra y paz",
    "Anna Karenina",
    "Los miserables",
    "Nuestra Señora de París",
    "El conde de Montecristo",
    "Los tres mosqueteros",
    "Madame Bovary",
    "La educación sentimental",
    "En busca del tiempo perdido",
    "Ulises",
    "Retrato del artista adolescente",
    "Dublineses",
    "La metamorfosis",
    "El proceso",
    "El castillo",
    "El gran Gatsby",
    "Suave es la noche",
    "Las uvas de la ira",
    "Al este del Edén",
    "Por quién doblan las campanas",
    "El viejo y el mar",
    "Fiesta",
    "El guardián entre el centeno",
    "Moby Dick",
    "Las aventuras de Huckleberry Finn",
    "La isla del tesoro",
    "Frankenstein",
    "Drácula"
]
?>