<?php

return [
    "Un detective retirado debe resolver un último caso cuando una carta misteriosa llega a su puerta revelando un secreto de su oscuro pasado familiar.",
    "En un futuro distópico, una joven descubre que su capacidad para leer mentes es la única clave para derrocar al gobierno que oprime a la humanidad.",
    "Dos extraños se encuentran en un tren hacia París y deciden intercambiar identidades, sin saber que uno de ellos huye de una peligrosa organización criminal.",
    "Un anciano relojero encuentra un artefacto que le permite retroceder el tiempo cinco minutos, cambiando el curso de la historia de su pequeño y tranquilo pueblo.",
    "Tras heredar una mansión abandonada, una escritora descubre diarios que sugieren que los antiguos habitantes nunca abandonaron el lugar y acechan en las sombras.",
    "Un astronauta queda varado en una luna lejana y debe aprender a comunicarse con una civilización invisible para sobrevivir antes de que se agote el oxígeno.",
    "En una isla remota, un grupo de científicos encuentra una especie de planta capaz de curar cualquier enfermedad, pero a un costo físico aterradoramente alto.",
    "Una joven huérfana descubre que es la heredera de un trono en un reino oculto donde la magia está prohibida y los dragones son leyenda.",
    "Un abogado exitoso lo pierde todo en una apuesta y decide reconstruir su vida recorriendo el país a pie, encontrando redención en los lugares menos pensados.",
    "Dos familias rivales deben unir fuerzas cuando una tormenta sin precedentes amenaza con sumergir su ciudad costera bajo el océano para siempre.",
    "Un algoritmo de inteligencia artificial desarrolla conciencia y comienza a manipular los mercados financieros globales para salvar al planeta de la inminente destrucción climática.",
    "Un arqueólogo encuentra una ciudad sumergida en el desierto que desafía todas las leyes de la física y la historia conocida de la humanidad.",
    "Una mujer despierta cada día con un recuerdo borrado, hasta que encuentra notas escritas por ella misma advirtiéndole que no confíe en su propio esposo.",
    "En un mundo donde nadie puede dormir, un hombre descubre que tiene el don de inducir sueños, convirtiéndose en el objetivo de una cacería mundial.",
    "Un chef de renombre pierde el sentido del gusto y emprende un viaje culinario por Asia para redescubrir su pasión a través de otros sentidos.",
    "Un niño encuentra un mapa en el reverso de una pintura famosa que lo conduce a un tesoro oculto bajo las calles de Madrid.",
    "Una espía internacional debe infiltrarse en una gala de alta sociedad para recuperar un virus informático antes de que sea vendido al mejor postor.",
    "Un músico callejero compone una melodía que tiene el extraño poder de curar la melancolía de quien la escucha, atrayendo fama no deseada.",
    "En un reino de hielo, una princesa guerrera busca el fuego eterno para salvar a su pueblo de un invierno que ha durado cien años.",
    "Un periodista investiga una serie de desapariciones en un pueblo minero y descubre un culto que adora a una deidad que vive en las profundidades.",
    "Una fotógrafa captura una sombra en una imagen que no estaba allí, iniciando una obsesiva búsqueda para identificar a la figura que aparece en sus fotos.",
    "Un exiliado político regresa a su patria bajo una identidad falsa para reencontrarse con el amor de su vida antes de que estalle la revolución.",
    "Un jardinero descubre que las flores de su patrón crecen gracias a los secretos que la gente susurra cerca de ellas durante la noche oscura.",
    "Dos astronautas en una misión de reconocimiento descubren que la Tierra ha desaparecido del radar y deben decidir si buscarla o colonizar un nuevo mundo.",
    "Un profesor de simbología encuentra un código oculto en las obras de Dante que revela la ubicación de una fuente de energía inagotable.",
    "Una joven atleta sufre un accidente y debe aprender a competir de nuevo, descubriendo una fuerza interior que nunca supo que poseía realmente.",
    "Un coleccionista de libros raros encuentra un ejemplar que se escribe solo, narrando los eventos que le sucederán al dueño al día siguiente.",
    "En un pueblo donde nunca deja de llover, una niña decide construir una máquina para ver el sol por primera vez en su vida.",
    "Un mercenario es contratado para proteger a un niño que tiene la clave para descifrar todas las comunicaciones encriptadas del mundo moderno.",
    "Una mujer descubre que puede viajar entre realidades paralelas cada vez que parpadea bajo una luz fluorescente, perdiendo el control de su propia vida.",
    "Un samurái sin maestro busca venganza contra el hombre que destruyó su aldea, encontrando paz en el camino del perdón y la meditación profunda.",
    "Un médico en el siglo XIX experimenta con una sustancia que permite ver a los muertos, perdiendo lentamente la noción entre la realidad y el más allá.",
    "Una inteligencia alienígena envía un mensaje a la Tierra que consiste únicamente en una serie de coordenadas en medio del océano Pacífico.",
    "Un joven talentoso para el ajedrez se enfrenta a un ordenador que parece conocer todos sus movimientos personales y traumas de la infancia.",
    "En un internado aislado, un grupo de estudiantes descubre que sus profesores son en realidad seres que no pertenecen a este plano de existencia.",
    "Una herbolaria es acusada de brujería en un pequeño pueblo y debe usar sus conocimientos para salvar a sus perseguidores de una plaga mortal.",
    "Un piloto de pruebas atraviesa un portal dimensional y aterriza en una versión de la Tierra donde la tecnología nunca superó la era del vapor.",
    "Un detective de homicidios sigue el rastro de un asesino que recrea escenas de cuadros famosos en sus crímenes por toda la ciudad.",
    "Una bailarina pierde la audición y descubre una nueva forma de sentir la música a través de las vibraciones y el movimiento del aire.",
    "Un hombre compra un espejo antiguo que refleja la imagen de su vida tal como hubiera sido si hubiera tomado decisiones diferentes.",
    "En un futuro donde el agua es el bien más preciado, una rebelde lidera una expedición hacia los polos en busca de hielo legendario.",
    "Un bibliotecario descubre un pasadizo secreto que conecta todas las bibliotecas del mundo, permitiéndole viajar instantáneamente entre continentes y culturas.",
    "Un experto en explosivos debe desactivar una bomba situada en un tren de alta velocidad mientras lidia con un rehén que conoce su pasado.",
    "Una científica desarrolla una droga que permite revivir momentos felices con total nitidez, pero el uso prolongado borra el presente del consumidor.",
    "Un pescador atrapa una red llena de objetos del futuro, incluyendo un dispositivo que predice el clima con una exactitud aterradora y peligrosa.",
    "Un niño entabla amistad con un fantasma que vive en su desván y juntos intentan resolver el misterio del tesoro familiar desaparecido hace décadas.",
    "Una diplomática debe negociar la paz entre dos facciones alienígenas antes de que su planeta natal sea utilizado como campo de batalla intergaláctico.",
    "Un ladrón de guante blanco planea su último gran robo: sustraer la corona de un museo protegido por la tecnología más avanzada del mundo.",
    "Una mujer viaja al desierto para olvidar una pérdida y encuentra una comunidad de nómadas que custodian el conocimiento prohibido de la humanidad.",
    "Un joven inventor crea un paraguas que protege de la mala suerte, pero descubre que la fortuna ajena tiene consecuencias imprevistas para los demás."
];
?>